### ISSUE TITLE
Error when running 'npm install'

### ISSUE THREAD

**Issue by AndrewKL** [Comcast/graphvinci#21]
while running 

> npm install

I got the following error message

```
npm WARN deprecated @codemirror/rangeset@0.19.5: As of 0.20.0, this package has been merged into @codemirror/state
npm WARN deprecated @codemirror/highlight@0.19.6: As of 0.20.0, this package has been split between @lezer/highlight and @codemirror/language
npm ERR! code 1
npm ERR! path /Users/loandrew/git/graphvinci/node_modules/lmdb-store
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@20.2.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.11.3 found at "/usr/local/opt/python@3.11/bin/python3.11"
npm ERR! gyp http GET https://nodejs.org/download/release/v20.2.0/node-v20.2.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v20.2.0/node-v20.2.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v20.2.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v20.2.0/SHASUMS256.txt
npm ERR! gyp info spawn /usr/local/opt/python@3.11/bin/python3.11
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/loandrew/git/graphvinci/node_modules/lmdb-store/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/loandrew/Library/Caches/node-gyp/20.2.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/loandrew/Library/Caches/node-gyp/20.2.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/loandrew/Library/Caches/node-gyp/20.2.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/loandrew/git/graphvinci/node_modules/lmdb-store',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
npm ERR! 
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
npm ERR! 
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
npm ERR! 
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:511:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Darwin 22.4.0
npm ERR! gyp ERR! command "/usr/local/Cellar/node/20.2.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/loandrew/git/graphvinci/node_modules/lmdb-store
npm ERR! gyp ERR! node -v v20.2.0
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in: /Users/loandrew/.npm/_logs/2023-06-16T20_36_01_271Z-debug-0.log
loandrew@88665a173757 graphvinci % npm -v
9.6.6
loandrew@88665a173757 graphvinci % node -v
v20.2.0
```

**Comment by AndrewKL** [comment]
https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a

> xcode-select --install

**Comment by AndrewKL** [comment]
more issues popped up after this

```
npm ERR! code 1
npm ERR! path /Users/loandrew/git/graphvinci/node_modules/lmdb-store
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! CXX(target) Release/obj.target/lmdb/src/node-lmdb.o
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@20.3.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.11.3 found at "/usr/local/opt/python@3.11/bin/python3.11"
npm ERR! gyp info spawn /usr/local/opt/python@3.11/bin/python3.11
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/loandrew/git/graphvinci/node_modules/lmdb-store/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/loandrew/Library/Caches/node-gyp/20.3.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/loandrew/Library/Caches/node-gyp/20.3.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/loandrew/Library/Caches/node-gyp/20.3.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/loandrew/git/graphvinci/node_modules/lmdb-store',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../src/node-lmdb.cpp:1:
npm ERR! In file included from ../src/node-lmdb.h:32:
npm ERR! In file included from ../../nan/nan.h:178:
npm ERR! ../../nan/nan_callbacks.h:55:23: error: no member named 'AccessorSignature' in namespace 'v8'
npm ERR! typedef v8::Local<v8::AccessorSignature> Sig;
npm ERR!                   ~~~~^
npm ERR! In file included from ../src/node-lmdb.cpp:1:
npm ERR! In file included from ../src/node-lmdb.h:32:
npm ERR! ../../nan/nan.h:684:39: warning: 'IdleNotificationDeadline' is deprecated: Use MemoryPressureNotification() to influence the GC schedule. [-Wdeprecated-declarations]
npm ERR!     return v8::Isolate::GetCurrent()->IdleNotificationDeadline(
npm ERR!                                       ^
npm ERR! /Users/loandrew/Library/Caches/node-gyp/20.3.0/include/node/v8-isolate.h:1291:3: note: 'IdleNotificationDeadline' has been explicitly marked deprecated here
npm ERR!   V8_DEPRECATE_SOON(
npm ERR!   ^
npm ERR! /Users/loandrew/Library/Caches/node-gyp/20.3.0/include/node/v8config.h:550:39: note: expanded from macro 'V8_DEPRECATE_SOON'
npm ERR! # define V8_DEPRECATE_SOON(message) [[deprecated(message)]]
npm ERR!                                       ^
npm ERR! In file included from ../src/node-lmdb.cpp:1:
npm ERR! In file included from ../src/node-lmdb.h:32:
npm ERR! ../../nan/nan.h:2544:8: error: no matching member function for call to 'SetAccessor'
npm ERR!   tpl->SetAccessor(
npm ERR!   ~~~~~^~~~~~~~~~~
npm ERR! /Users/loandrew/Library/Caches/node-gyp/20.3.0/include/node/v8-template.h:816:8: note: candidate function not viable: no known conversion from 'imp::Sig' (aka 'int') to 'v8::SideEffectType' for 7th argument
npm ERR!   void SetAccessor(
npm ERR!        ^
npm ERR! /Users/loandrew/Library/Caches/node-gyp/20.3.0/include/node/v8-template.h:809:8: note: candidate function not viable: no known conversion from 'imp::NativeGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'v8::AccessorGetterCallback' (aka 'void (*)(Local<v8::String>, const PropertyCallbackInfo<v8::Value> &)') for 2nd argument
npm ERR!   void SetAccessor(
npm ERR!        ^
npm ERR! 1 warning and 2 errors generated.
npm ERR! make: *** [Release/obj.target/lmdb/src/node-lmdb.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:511:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Darwin 22.4.0
npm ERR! gyp ERR! command "/usr/local/Cellar/node/20.3.0_1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/loandrew/git/graphvinci/node_modules/lmdb-store
npm ERR! gyp ERR! node -v v20.3.0
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok

```

this is partially resolved by doing the following...

```
npm install -g npm-check-updates
npm-check-updates -u

```

which gets 

```
loandrew@88665a173757 graphvinci % npm-check-updates -u

Upgrading /Users/loandrew/git/graphvinci/package.json
[====================] 16/16 100%

 @babel/plugin-transform-modules-commonjs  ^7.15.4  →  ^7.22.5
 @parcel/transformer-image                  ^2.0.0  →   ^2.9.2
 codemirror                                ^5.65.0  →   ^6.0.1
 codemirror-graphql                        ^1.2.11  →   ^2.0.8
 d3                                        ^5.16.0  →   ^7.8.5
 graphql                                   ^15.6.0  →  ^16.6.0
 jest                                      ^27.2.1  →  ^29.5.0
 madge                                      ^5.0.1  →   ^6.1.0
 markdown-it                               ^12.3.2  →  ^13.0.1
 monaco-editor                             ^0.31.0  →  ^0.39.0
 parcel                                     ^2.0.0  →   ^2.9.2
 parcel-reporter-static-files-copy          ^1.3.0  →   ^1.5.0
 prettier                                   ^2.5.1  →   ^2.8.8
 split.js                                   ^1.6.4  →   ^1.6.5
```

which gets too...

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @Comcast/GraphVinci@1.0.1
npm ERR! Found: codemirror@6.0.1
npm ERR! node_modules/codemirror
npm ERR!   codemirror@"^6.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer codemirror@"^5.65.3" from codemirror-graphql@2.0.8
npm ERR! node_modules/codemirror-graphql
npm ERR!   codemirror-graphql@"^2.0.8" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by wivaku** [comment]
Same.

```
npm install

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: codemirror-graphql@2.0.9
npm ERR! Found: codemirror@6.0.1
npm ERR! node_modules/codemirror
npm ERR!   codemirror@"^6.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer codemirror@"^5.65.3" from codemirror-graphql@2.0.9
npm ERR! node_modules/codemirror-graphql
npm ERR!   codemirror-graphql@"^2.0.9" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: codemirror@5.65.13
npm ERR! node_modules/codemirror
npm ERR!   peer codemirror@"^5.65.3" from codemirror-graphql@2.0.9
npm ERR!   node_modules/codemirror-graphql
npm ERR!     codemirror-graphql@"^2.0.9" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

When using the suggested `--force` or `--legacy-peer-deps`, npm install completes successfully.
But then `npm start` fails:
```
npm start

> @Comcast/GraphVinci@1.0.1 start
> parcel serve index.html --open

Server running at http://localhost:1234
🚨 Build failed.

@parcel/transformer-css: Unexpected token Delim('/')

.../graphvinci/modules/styles/app.css:272:5
    271 |     width: 100%;
  > 272 |     //border: 2px solid #aaa;
  >     |     ^
    273 |     border: none;
    274 |     //border-radius: 10px
```
